### ISSUE TITLE
Rename repo/types to align with JWS

### ISSUE THREAD

**Issue by msporny** [transmute-industries/lds-jws2020#5]
Please rename the following things in this library:

lds-jose2020 -> lds-jws2020
JoseVerificationKey2020 -> JwsVerificationKey2020
JoseLinkedDataSignature2020 -> JsonWebSignature2020

JOSE stands for "Json Object Signing and Encryption" -- this library doesn't do encryption, it does signatures, and that is the Json Web Signature part of the JOSE stack.

**Comment by OR13** [comment]
Thanks, totally agree with these name change suggestions.
