### ISSUE TITLE
Digest algorithm

### ISSUE THREAD

**Issue by llorllale** [transmute-industries/lds-jws2020#9]
Where is the canonical definition of the digest algorithm defined by the [vocabulary](https://lds.jsld.org/contexts/#JsonWebSignature2020):

```
{
  "id": "https://lds.jsld.org/contexts/#JsonWebSignature2020",
  "type": "SignatureSuite",
  "canonicalizationAlgorithm": "https://w3id.org/security#URDNA2015",
  "digestAlgorithm": "https://www.ietf.org/assignments/jwa-parameters#SHA256",
  "signatureAlgorithm": "https://tools.ietf.org/html/rfc7518"
}
```

`https://www.ietf.org/assignments/jwa-parameters#SHA256` is not a valid URL, and JWA does not define message-digest algorithms.

**Comment by OR13** [comment]
@llorllale I'm about to address (close) this, but its worth pointing out that JWS do use digests, and that they may differ from the digest used on the canonization of JSON-LD.

https://www.iana.org/assignments/jose/jose.xhtml#web-signature-encryption-algorithms

https://w3c-ccg.github.io/ld-proofs/#dfn-message-digest-algorithm
